runtime: python39

service: default

# https://cloud.google.com/appengine/docs/standard#instance_classes
#instance_class: B4

basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
- url: /.*
  script: main.app

