runtime: python39
api_version: 1
threadsafe: true

service: agora-recommendation-handler

# https://cloud.google.com/appengine/docs/standard#instance_classes
#instance_class: B4

basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 2.1.3
